// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<PingResponse>("ping"),
	getConfig: () => __TAURI_INVOKE<ConfigDto>("get_config"),
	setConfigValue: (request: SetConfigRequest) => __TAURI_INVOKE<null>("set_config_value", { request }),
	testAiConnection: () => __TAURI_INVOKE<ConnectionTestResult>("test_ai_connection"),
	/**
	 *  Scans the given sources and returns the video/subtitle counts for the Step 1
	 *  preview. Empty counts are a valid result the UI blocks on, not an error.
	 */
	listSourceFiles: (paths: string[]) => __TAURI_INVOKE<SourceScanResult>("list_source_files", { paths }),
	/**
	 *  Runs a cancellable AI analysis over the sources with the chosen relocation
	 *  mode, pushing staged progress over `on_progress`, and returns the plan.
	 */
	analyzeSources: (paths: string[], relocationMode: RelocationModeDto, onProgress: Channel<MatchProgress>) => __TAURI_INVOKE<MatchPlanDto>("analyze_sources", { paths, relocationMode, onProgress }),
	/**  Aborts a running analysis and discards the pending plan (design D3). */
	cancelAnalysis: () => __TAURI_INVOKE<null>("cancel_analysis"),
	/**  Executes exactly the selected operations of a plan and reports each outcome. */
	executeSelected: (planId: string, operationIds: number[]) => __TAURI_INVOKE<ExecutionReportDto>("execute_selected", { planId, operationIds }),
	/**
	 *  Scans the given sources and returns the subtitle count for the Step 1
	 *  preview. An empty count is a valid result the UI blocks on, not an error.
	 */
	listConvertInputs: (paths: string[]) => __TAURI_INVOKE<ConvertScanResult>("list_convert_inputs", { paths }),
	/**
	 *  Resolves every output path for the chosen options and stores the resulting
	 *  plan, returning it for review in Step 2.
	 */
	previewConversion: (paths: string[], options: ConvertOptionsDto) => __TAURI_INVOKE<ConvertPlanDto>("preview_conversion", { paths, options }),
	/**
	 *  Converts exactly the selected items of a plan, reporting per-file progress
	 *  over `on_progress`, and returns each item's outcome.
	 */
	executeConversion: (planId: string, itemIds: number[], onProgress: Channel<ConvertProgress>) => __TAURI_INVOKE<ConversionReportDto>("execute_conversion", { planId, itemIds, onProgress }),
	/**  Stops a running batch before its next file and discards the pending plan. */
	cancelConversion: () => __TAURI_INVOKE<null>("cancel_conversion"),
};

/* Types */
/**
 *  The AI section of the shared CLI configuration, as shown in the GUI.
 * 
 *  The API key never crosses the IPC boundary in cleartext: only its masked
 *  form does, and there is no command that returns the raw value.
 */
export type AiConfigDto = {
	/**  Canonical provider id (`openai`, `openrouter`, `azure-openai`, `local`). */
	provider: string,
	model: string,
	baseUrl: string,
	/**  Masked key (e.g. `****abcd`), empty when no key is configured. */
	apiKeyMasked: string,
	/**
	 *  Whether a key is configured at all — distinguishes "unset" from a key
	 *  too short to produce a meaningful mask.
	 */
	apiKeySet: boolean,
};

/**
 *  Configuration as presented by `get_config`.
 * 
 *  Grouped by config-file section so later changes can add sections without
 *  reshaping what the settings screen already reads.
 */
export type ConfigDto = {
	ai: AiConfigDto,
};

/**
 *  Outcome of an explicit AI connection test.
 * 
 *  A rejected connection is a result, not a command failure, so the command
 *  resolves with `ok: false` and an embedded `ErrorDto` the frontend localizes
 *  through the same path as any other error.
 */
export type ConnectionTestResult = {
	ok: boolean,
	/**
	 *  Round-trip time of the probe request; present only on success.
	 * 
	 *  `u32`, not `u64`: this crosses into JavaScript, whose numbers are f64 and
	 *  exact only to 2^53. Specta refuses to export a 64-bit integer as `number`
	 *  for that reason, and it is right to — the hand-written mirror this
	 *  replaces declared `latencyMs?: number` and quietly claimed a range the
	 *  receiver cannot represent. A probe latency has no use for more than the
	 *  49 days `u32` milliseconds already covers.
	 */
	latencyMs: number | null,
	/**  Why the test failed; present only on failure. */
	error: ErrorDto | null,
};

/**  One item's outcome in the Step 3 report. */
export type ConversionOutcomeDto = {
	inputName: string,
	outputPath: string,
	status: ConversionStatusDto,
	/**  Whether the write replaced a file that already existed (design D3). */
	overwritten: boolean,
	/**
	 *  Whether the input was removed afterwards, i.e. keep-original was off and
	 *  the removal succeeded (design D4).
	 */
	originalRemoved: boolean,
	/**  Why the item failed, localizable through the shared error path. */
	error: ErrorDto | null,
	/**
	 *  A non-fatal problem — today only "the conversion succeeded but the
	 *  original could not be removed", which the CLI discards and the GUI must
	 *  not, since it would otherwise misstate what is on disk (design D4).
	 */
	warning: ErrorDto | null,
};

/**  The final report returned by `execute_conversion`. */
export type ConversionReportDto = {
	outcomes: ConversionOutcomeDto[],
	successCount: number,
	failureCount: number,
	/**
	 *  True when the user stopped the batch; the `Cancelled` outcomes are the
	 *  items that were never started.
	 */
	cancelled: boolean,
};

/**  What became of one item in the batch. */
export type ConversionStatusDto = "converted" | "failed" | 
/**  Excluded by the plan (`skip_reason`) and refused by the executor. */
"skipped" | 
/**  Never started: the batch was cancelled before reaching it (design D5). */
"cancelled";

/**
 *  Target format of a conversion run.
 * 
 *  Exactly the four the crate can serialize; SMI and LRC stay readable inputs
 *  with no way to become outputs, so offering them would be a dead choice.
 */
export type ConvertFormatDto = "srt" | "ass" | "vtt" | "sub";

/**
 *  One planned conversion, referenced by the frontend via `id` only.
 * 
 *  `id` is the item's index in the backend-held plan. `skip_reason` carries a
 *  stable code (`convert.already_target_format`, `convert.output_collision`)
 *  when the item cannot run; such items are excluded from execution, and the
 *  skip is evaluated before `output_exists` so a skipped item is never *also*
 *  presented as an overwrite (design D2).
 */
export type ConvertItemDto = {
	id: number,
	inputName: string,
	inputPath: string,
	outputPath: string,
	outputExists: boolean,
	skipReason: string | null,
};

/**
 *  The options a preview is computed from.
 * 
 *  `target_format` is optional because the wizard's Step 2 has to render the
 *  configured default before the user has chosen anything: a `null` means
 *  "resolve `formats.default_output` from the shared config", and the resulting
 *  plan echoes back what was used (design D6).
 */
export type ConvertOptionsDto = {
	targetFormat: ConvertFormatDto | null,
	keepOriginal: boolean,
};

/**
 *  The plan Step 2 renders, returned by `preview_conversion`.
 * 
 *  `plan_id` ties a later `execute_conversion` back to this exact preview; a
 *  newer preview replaces it and the old id becomes stale (design D1).
 */
export type ConvertPlanDto = {
	planId: string,
	/**
	 *  The format actually used, including when the request left it to the
	 *  configuration (design D6).
	 */
	targetFormat: ConvertFormatDto,
	keepOriginal: boolean,
	items: ConvertItemDto[],
};

/**
 *  A progress message pushed over the execution `Channel`.
 * 
 *  Per file, never finer: the crate converts a whole file in one call and
 *  reports nothing from inside it, so a percentage would be invented.
 */
export type ConvertProgress = {
	stage: ConvertStage,
	/**  1-based position of `file_name` in the batch; equals `total` on `Finished`. */
	index: number,
	total: number,
	fileName: string,
};

/**
 *  Scan preview returned by `list_convert_inputs` before any plan exists.
 * 
 *  A count is all Step 1 needs; the file list — which includes temporary
 *  archive-extraction paths — never leaves the backend.
 */
export type ConvertScanResult = {
	subtitleCount: number,
};

/**  Where a batch is, as reported to Step 3 (design D5). */
export type ConvertStage = "converting" | 
/**
 *  The batch stopped, whether it finished or was cancelled. The report the
 *  command resolves with is what says which.
 */
"finished";

/**
 *  Structured error crossing the Tauri IPC boundary.
 * 
 *  Every command returns `Result<T, ErrorDto>`.
 */
export type ErrorDto = {
	/**  Stable machine-readable code, used as a localization key (e.g. `config.invalid_provider`). */
	code: string,
	/**  Raw English message for detail display; never shown as the primary text. */
	message: string,
	/**  Optional stable code for a recovery hint, also resolved by the frontend. */
	hintCode: string | null,
};

/**
 *  One executed operation's outcome in the Step 4 report.
 * 
 *  `error` carries a localizable `ErrorDto` (its `code` reuses the shared
 *  `core.<category>` keys) so a per-item failure renders the same way as any
 *  other error, without aborting the run (design D8).
 */
export type ExecutionOutcomeDto = {
	subtitleName: string,
	targetPath: string,
	applied: boolean,
	error: ErrorDto | null,
};

/**  The final execution report returned by `execute_selected`. */
export type ExecutionReportDto = {
	outcomes: ExecutionOutcomeDto[],
	successCount: number,
	failureCount: number,
};

/**
 *  One proposed match operation, referenced by the frontend via `id` only.
 * 
 *  `id` is the operation's index in the backend-held plan; the canonical
 *  `MatchOperation` never crosses IPC (design D1). `confidence` is a whole
 *  percentage `0..=100` rather than the crate's `0.0..=1.0` `f32`, so the
 *  review UI has nothing to round.
 */
export type MatchOperationDto = {
	id: number,
	subtitleName: string,
	targetPath: string,
	confidence: number,
	/**  The AI's reasoning, shown verbatim (design D7). */
	reasoning: string[],
};

/**
 *  The reviewable plan the frontend renders in Step 3.
 * 
 *  `plan_id` ties a later `execute_selected` back to this exact analysis; a
 *  newer analysis replaces it and the old id becomes stale (design D1).
 */
export type MatchPlanDto = {
	planId: string,
	relocationMode: RelocationModeDto,
	videos: MatchedVideoDto[],
	/**  Videos in the scan referenced by no operation (design D6). */
	unmatchedVideos: string[],
	/**  Subtitles in the scan referenced by no operation (design D6). */
	unmatchedSubtitles: string[],
};

/**
 *  A progress message pushed over the analysis `Channel` (design D2).
 * 
 *  The wizard reports progress through a per-invocation `tauri::ipc::Channel`
 *  rather than a `tauri_specta::Event`. A command that emits an `Event` must
 *  hold a runtime-generic `AppHandle<R>`, and a generic command cannot be
 *  registered in the single runtime-generic `specta_builder` that
 *  `add-typed-ipc-bindings` locked in — the macro cannot infer `R`. A `Channel`
 *  is runtime-agnostic, keeps the command non-generic, and scopes progress to
 *  the one analysis that owns it. See design D2.
 */
export type MatchProgress = {
	stage: MatchStage,
};

/**
 *  Analysis stage reported to the UI's staged indicator (design D2).
 * 
 *  `Analyzing` is deliberately neutral: `match_file_list_with_audit` may
 *  resolve from the crate's cache with no AI request, and the label must not
 *  claim one happened.
 */
export type MatchStage = "scanning" | "analyzing" | "finalizing";

/**
 *  A video with at least one matched subtitle (design D7).
 * 
 *  Videos with no match appear only in `MatchPlanDto::unmatched_videos`, never
 *  here.
 */
export type MatchedVideoDto = {
	videoName: string,
	matches: MatchOperationDto[],
};

/**  Response of the `ping` reference command. */
export type PingResponse = {
	/**  Always `"pong"`. */
	message: string,
	/**  The GUI application version. */
	appVersion: string,
};

/**
 *  Relocation mode chosen in Step 1 of the match wizard.
 * 
 *  Maps onto `subx_cli`'s `FileRelocationMode`: `Rename` is the crate's `None`
 *  (rename the subtitle in place) and is the wizard's default. The mode is
 *  baked into every operation at analysis time (design D4), so it is picked
 *  before analysis and echoed back on the plan for the Step 4 summary.
 */
export type RelocationModeDto = "rename" | "copy" | "move";

/**
 *  A single `key = value` write against the shared configuration.
 * 
 *  Writes are per-key, mirroring `subx-cli config set <key> <value>`; the
 *  settings screen sends one request per changed field.
 */
export type SetConfigRequest = {
	/**  Dotted config key, e.g. `ai.provider`. */
	key: string,
	value: string,
};

/**
 *  Scan preview returned by `list_source_files` before any AI call.
 * 
 *  Counts are enough for the Step 1 preview and the insufficient-sources gate;
 *  the canonical file lists never leave the backend (they include temporary
 *  archive-extraction paths that must not become the frontend's concern).
 */
export type SourceScanResult = {
	videoCount: number,
	subtitleCount: number,
};

