// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<PingResponse>("ping"),
	getConfig: () => __TAURI_INVOKE<ConfigDto>("get_config"),
	setConfigValue: (request: SetConfigRequest) => __TAURI_INVOKE<null>("set_config_value", { request }),
	testAiConnection: () => __TAURI_INVOKE<ConnectionTestResult>("test_ai_connection"),
};

/* Types */
/**
 *  The AI section of the shared CLI configuration, as shown in the GUI.
 * 
 *  The API key never crosses the IPC boundary in cleartext: only its masked
 *  form does, and there is no command that returns the raw value.
 */
export type AiConfigDto = {
	/**  Canonical provider id (`openai`, `openrouter`, `azure-openai`, `local`). */
	provider: string,
	model: string,
	baseUrl: string,
	/**  Masked key (e.g. `****abcd`), empty when no key is configured. */
	apiKeyMasked: string,
	/**
	 *  Whether a key is configured at all — distinguishes "unset" from a key
	 *  too short to produce a meaningful mask.
	 */
	apiKeySet: boolean,
};

/**
 *  Configuration as presented by `get_config`.
 * 
 *  Grouped by config-file section so later changes can add sections without
 *  reshaping what the settings screen already reads.
 */
export type ConfigDto = {
	ai: AiConfigDto,
};

/**
 *  Outcome of an explicit AI connection test.
 * 
 *  A rejected connection is a result, not a command failure, so the command
 *  resolves with `ok: false` and an embedded `ErrorDto` the frontend localizes
 *  through the same path as any other error.
 */
export type ConnectionTestResult = {
	ok: boolean,
	/**
	 *  Round-trip time of the probe request; present only on success.
	 * 
	 *  `u32`, not `u64`: this crosses into JavaScript, whose numbers are f64 and
	 *  exact only to 2^53. Specta refuses to export a 64-bit integer as `number`
	 *  for that reason, and it is right to — the hand-written mirror this
	 *  replaces declared `latencyMs?: number` and quietly claimed a range the
	 *  receiver cannot represent. A probe latency has no use for more than the
	 *  49 days `u32` milliseconds already covers.
	 */
	latencyMs: number | null,
	/**  Why the test failed; present only on failure. */
	error: ErrorDto | null,
};

/**
 *  Structured error crossing the Tauri IPC boundary.
 * 
 *  Every command returns `Result<T, ErrorDto>`.
 */
export type ErrorDto = {
	/**  Stable machine-readable code, used as a localization key (e.g. `config.invalid_provider`). */
	code: string,
	/**  Raw English message for detail display; never shown as the primary text. */
	message: string,
	/**  Optional stable code for a recovery hint, also resolved by the frontend. */
	hintCode: string | null,
};

/**  Response of the `ping` reference command. */
export type PingResponse = {
	/**  Always `"pong"`. */
	message: string,
	/**  The GUI application version. */
	appVersion: string,
};

/**
 *  A single `key = value` write against the shared configuration.
 * 
 *  Writes are per-key, mirroring `subx-cli config set <key> <value>`; the
 *  settings screen sends one request per changed field.
 */
export type SetConfigRequest = {
	/**  Dotted config key, e.g. `ai.provider`. */
	key: string,
	value: string,
};

